apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zyv1s7slb-nodejs
  janus-idp.io/tekton: zyv1s7slb-nodejs
  backstage.io/kubernetes-id: zyv1s7slb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zyv1s7slb-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
