apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zyv1s7slb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zyv1s7slb-nodejs 
  name: zyv1s7slb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zyv1s7slb-nodejs 
